// src/lib/components/ConfirmDialog.svelte
<script lang="ts">
	let {
		open,
		title,
		message,
		confirmLabel = 'Confirm',
		onconfirm,
		oncancel
	}: {
		open: boolean;
		title: string;
		message: string;
		confirmLabel?: string;
		onconfirm: () => void;
		oncancel: () => void;
	} = $props();

	let dialogEl: HTMLDialogElement | undefined = $state();

	$effect(() => {
		if (!dialogEl) return;
		if (open && !dialogEl.open) {
			dialogEl.showModal();
		} else if (!open && dialogEl.open) {
			dialogEl.close();
		}
	});

	function handleClose() {
		oncancel();
	}
</script>

<dialog bind:this={dialogEl} onclose={handleClose}>
	<div class="dialog-content">
		<h3>{title}</h3>
		<p>{message}</p>
		<div class="dialog-actions">
			<button class="btn-ghost" onclick={oncancel}>Cancel</button>
			<button class="btn-danger" onclick={onconfirm}>{confirmLabel}</button>
		</div>
	</div>
</dialog>

<style>
	dialog {
		background: var(--bg-secondary);
		color: var(--text-primary);
		border: 1px solid var(--border-light);
		border-radius: var(--radius-lg);
		padding: 0;
		max-width: 420px;
		width: 90vw;
		box-shadow: var(--shadow-lg);
	}

	dialog::backdrop {
		background: rgba(0, 0, 0, 0.7);
	}

	.dialog-content {
		padding: 1.5rem;
	}

	h3 {
		font-size: 1.1rem;
		font-weight: 600;
		margin-bottom: 0.5rem;
	}

	p {
		font-size: 0.9rem;
		color: var(--text-secondary);
		line-height: 1.5;
		margin-bottom: 1.5rem;
	}

	.dialog-actions {
		display: flex;
		justify-content: flex-end;
		gap: 0.5rem;
	}
</style>

// src/components/ConfirmDialog.tsx
'use client';

import { useEffect, useRef } from 'react';

type Props = {
	open: boolean;
	title: string;
	message: string;
	confirmLabel?: string;
	busy?: boolean;
	onConfirm: () => void;
	onCancel: () => void;
};

export function ConfirmDialog({
	open,
	title,
	message,
	confirmLabel = 'Confirm',
	busy = false,
	onConfirm,
	onCancel
}: Props) {
	const dialogRef = useRef<HTMLDialogElement>(null);

	useEffect(() => {
		const dialog = dialogRef.current;
		if (!dialog) return;
		if (open && !dialog.open) dialog.showModal();
		if (!open && dialog.open) dialog.close();
	}, [open]);

	// close() from the effect above also fires `close`; only a dismissal by the
	// user (Escape) reaches this handler while the parent still considers it open.
	function handleClose() {
		if (open) onCancel();
	}

	return (
		<dialog
			ref={dialogRef}
			onClose={handleClose}
			className="border-line bg-surface text-ink m-auto w-[calc(100%-2rem)] max-w-sm rounded-lg border p-5 backdrop:bg-black/60"
		>
			<h2 className="text-sm font-semibold">{title}</h2>
			<p className="text-ink-secondary mt-2 text-sm">{message}</p>

			<div className="mt-5 flex justify-end gap-2">
				<button type="button" className="btn-ghost btn-sm" onClick={onCancel} disabled={busy}>
					Cancel
				</button>
				<button type="button" className="btn-danger btn-sm" onClick={onConfirm} disabled={busy}>
					{confirmLabel}
				</button>
			</div>
		</dialog>
	);
}
