// src/lib/components/ExposureCanvas.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { ExposureRenderer, type AdjustmentParams } from '$lib/webgl/exposure-renderer.js';

	let {
		src,
		alt,
		adjustments,
		class: className = ''
	}: {
		src: string;
		alt: string;
		adjustments: AdjustmentParams;
		class?: string;
	} = $props();

	let canvasEl: HTMLCanvasElement | undefined = $state();
	let renderer: ExposureRenderer | null = $state(null);
	let fallback = $state(false);
	let currentSrc = $state('');

	onMount(() => {
		if (!canvasEl) return;
		try {
			renderer = new ExposureRenderer(canvasEl);
		} catch {
			fallback = true;
		}
	});

	onDestroy(() => {
		renderer?.destroy();
	});

	$effect(() => {
		if (!renderer || !src) return;
		if (src === currentSrc) return;

		const img = new Image();
		img.crossOrigin = 'anonymous';
		const target = src;
		img.onload = () => {
			if (target !== src) return;
			renderer?.loadImage(img);
			renderer?.render(adjustments);
			currentSrc = target;
		};
		img.src = target;
	});

	$effect(() => {
		if (!renderer || !currentSrc) return;
		renderer.render(adjustments);
	});
</script>

{#if fallback}
	<img
		{src}
		{alt}
		class={className}
		draggable="false"
		style:filter={adjustments.exposure !== 0
			? `brightness(${Math.pow(2, adjustments.exposure)})`
			: undefined}
	/>
{:else}
	<canvas
		bind:this={canvasEl}
		class={className}
		draggable="false"
		aria-label={alt}
	></canvas>
{/if}

// src/components/ExposureCanvas.tsx
'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { ExposureRenderer, type AdjustmentParams } from '@/lib/webgl/exposure-renderer';

interface ExposureCanvasProps {
	src: string;
	alt: string;
	adjustments: AdjustmentParams;
	className?: string;
}

export function ExposureCanvas({ src, alt, adjustments, className }: ExposureCanvasProps) {
	const canvasRef = useRef<HTMLCanvasElement | null>(null);
	const rendererRef = useRef<ExposureRenderer | null>(null);
	const adjustmentsRef = useRef(adjustments);
	const [fallback, setFallback] = useState(false);
	const [loadedSrc, setLoadedSrc] = useState('');

	useEffect(() => {
		adjustmentsRef.current = adjustments;
	}, [adjustments]);

	// A callback ref rather than an effect: the renderer must exist before the
	// image-loading effect below runs, and failing over to <img> is a decision
	// made at attach time, not a synchronisation step.
	const attachCanvas = useCallback((canvas: HTMLCanvasElement | null) => {
		canvasRef.current = canvas;

		if (!canvas) {
			rendererRef.current?.destroy();
			rendererRef.current = null;
			return;
		}

		try {
			rendererRef.current = new ExposureRenderer(canvas);
		} catch {
			setFallback(true);
		}
	}, []);

	useEffect(() => {
		const renderer = rendererRef.current;
		if (!renderer || !src) return;

		let stale = false;
		const image = new Image();
		image.crossOrigin = 'anonymous';
		image.onload = () => {
			if (stale) return;
			renderer.loadImage(image);
			renderer.render(adjustmentsRef.current);
			setLoadedSrc(src);
		};
		image.src = src;

		return () => {
			stale = true;
		};
	}, [src]);

	useEffect(() => {
		const renderer = rendererRef.current;
		if (!renderer || !loadedSrc) return;
		renderer.render(adjustments);
	}, [adjustments, loadedSrc]);

	if (fallback) {
		// eslint-disable-next-line @next/next/no-img-element
		return <img src={src} alt={alt} className={className} draggable={false} />;
	}

	return <canvas ref={attachCanvas} className={className} draggable={false} aria-label={alt} />;
}
